name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t my-app .

      # Étape 4 : Lancer les tests
      - name: Run tests
        run: docker run my-app npm test

      # Étape 5 : Pousser l'image sur Docker Hub (si configuré)
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Étape 6 : Déploiement sur Render (si configuré)
      - name: Deploy to Render
        run: |
          curl -fsSL https://render.com/cli/install.sh | bash
          export PATH="$HOME/.render/bin:$PATH"
          render login
          render deploy --docker --name my-app --env production
